name = "StackedSearch"
uuid = "733b57af-1f25-4f02-9c37-06ad12c51e4b"
authors = ["Eric S. Tellez <donsadit@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
